name: Sync with Genesis
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
jobs:
  check-releases:
    name: Latest Genesis Data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: sergeidyga/checkout-dirs@v1
        with:
           dirs: 'genesis transactions'
           repository: anoma/namada-mainnet-genesis

      - uses: casperdcl/push-dir@v1
        with:
          message: update static site
          branch: gh-pages
          dir: transactions
          history: false
